name: e2e-playwright
on:
  workflow_call:
    inputs:
      start-cmd:
        description: Command to start the server in the background.
        type: string
        required: true
      url:
        description: URL to wait for before running e2e.
        type: string
        default: http://localhost:3000
      install-cmd:
        type: string
        default: npm install
      node-version:
        type: string
        default: "22"
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with: { node-version: '${{ inputs.node-version }}' }
      - run: ${{ inputs.install-cmd }}
      - name: cache browsers
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/package.json') }}
      - run: npx playwright-core install --with-deps chromium
      - run: ${{ inputs.start-cmd }} &
        name: start server
      - name: wait for server
        run: until curl -sf '${{ inputs.url }}' >/dev/null 2>&1; do sleep 1; done
        timeout-minutes: 1
      - run: npm run e2e
        env: { BASE_URL: '${{ inputs.url }}' }
